name: geo_bertopic_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.8
  - pandas=2.2.1
  - numpy=1.26.2
  - scipy=1.11.4
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - scikit-learn=1.3.2
  - statsmodels=0.14.4
  - geopandas=1.0.1
  - fiona=1.9.6
  - shapely=2.0.3
  - pyproj=3.6.1
  - rasterio=1.3.10
  - h3-py=3.7.7
  - regex=2023.10.3
  - emoji=2.12.1
  - jupyterlab=4.0.9
  - ipykernel=6.26.0
  - notebook=7.0.6
  - tqdm=4.66.1
  - pip=23.3.1
  - pip:
      - accelerate==0.29.1
      - altair==5.5.0
      - bertopic==0.16.4
      - bpemb==0.3.5
      - dash==2.17.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - emoji==2.12.1
      - flair==0.13.1
      - h3==3.7.7
      - huggingface-hub==0.22.2
      - janome==0.5.0
      - keyphrase-vectorizers==0.0.11
      - nltk==3.8.1
      - numba==0.61.0
      - numpy==1.26.2
      - octis==1.14.0
      - plotly==5.18.0
      - pydeck==0.9.1
      - pyarrow==18.1.0
      - pynndescent==0.5.11
      - regex==2023.10.3
      - requests==2.32.3
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - spacy==3.7.2
      - spacy-transformers==1.3.4
      - streamlit==1.41.0
      - streamlit-folium==0.23.2
      - torch==2.1.1
      - torchvision==0.16.1
      - transformers==4.36.2
      - umap-learn==0.5.5
      - wikipedia-api==0.6.0
      - wordcloud==1.9.3